# ########################################################################
#
# Ricgraph - Research in context graph
#
# ########################################################################
#
# MIT License
#
# Copyright (c) 2024 Rik D.T. Janssen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# ########################################################################
#
# This file is the OpenAPI specification file, the REST API
# for Ricgraph and Ricgraph Explorer.
# For the OpenAPI format specification,
# see https://spec.openapis.org/oas/latest.html.
#
# Original version Rik D.T. Janssen, May 2024.
#
# ########################################################################

openapi: 3.0.0
info:
  title: "Ricgraph - Research in context graph REST API"
  version: 1.0.0
  description: "
              ### What to find on this page?
              
              This is the documentation page for the Ricgraph REST API. 
              You can use the Ricgraph REST API to programmatically get
              items from Ricgraph, as an alternative to using the user interface.
              You will get these items in a 
              [JSON format](https://en.wikipedia.org/wiki/JSON).
              
              ### How to use
              
              In the left column of this page, you can explore the calls 
              (i.e., the REST API operations) 
              that are available. You can also try them out, by selecting a call,
              entering values in the 'Query-string parameters' subsection
              of the 'Request' section,
              and clicking the 'Try' button.
              Next, a gray tabbed box will appear.
              In the 'Response' tab of that box, you will get the JSON response.
              In the 'CURL' tab of that box, you will get a
              [curl](https://en.wikipedia.org/wiki/CURL#curl) call with an
              [URL](https://en.wikipedia.org/wiki/URL) (web link) that
              you can use in a browser or in your code.
              
              You don't need to provide authentication to use these calls.
              
              ### Technicalities
              
              The Ricgraph REST API uses 
              the [OpenAPI standard](https://www.openapis.org).
              It gives access to Ricgraph function calls both in *ricgraph.py* 
              and in *ricgraph_explorer.py*. 
              
              Read more about [REST (representational state transfer)](https://en.wikipedia.org/wiki/REST), or
              read more about [API (application programming interface)](https://en.wikipedia.org/wiki/API).
              "
  contact:
    name: Support for questions or improvements
    url: https://github.com/UtrechtUniversity/ricgraph
  license:
    name: MIT License
    url: https://github.com/UtrechtUniversity/ricgraph/blob/main/LICENSE

externalDocs:
  url: https://doi.org/10.1016/j.softx.2024.101736
  description: "Reference publication: Rik D.T. Janssen (2024). Ricgraph: A flexible and extensible graph to
                explore research in context from various systems. SoftwareX, 26(101736).
                https://doi.org/10.1016/j.softx.2024.101736."

servers:
  - url: "/api"

components:
  parameters:
    name:
      name: "name"
      description: "Search for a value in Ricgraph field *name*"
      in: query
      required: False
      schema:
        type: "string"
    category:
      name: "category"
      description: "Search for a value in Ricgraph field *category*"
      in: query
      required: False
      schema:
        type: "string"
    value:
      name: "value"
      description: "Search for a value in Ricgraph field *value*"
      in: query
      required: False
      schema:
        type: "string"
    key:
      name: "key"
      description: "Search for a value in Ricgraph field *_key*"
      in: query
      required: True
      schema:
        type: "string"
    max_nr_items:
      name: "max_nr_items"
      description: "The maximum number of items to return, or 0 to return all items"
      in: query
      required: False
      schema:
        type: "string"
        default: "250"      # This is MAX_ITEMS from ricgraph_explorer.py.
    source_system:
      name: "source_system"
      description: "The name of the source system you would like to enrich"
      in: query
      required: True
      schema:
        type: "string"
    name_want:
      name: "name_want"
      description: "Return only neighbor nodes whose field *name* matches any value 
                    in the provided list; if the list is empty, return all neighbor nodes 
                    regardless of their field *name*"
      in: query
      required: False
      schema:
        type: "array"
        items:
          type: "string"
          default: ""          # To prevent the word 'string' in the input field.
    name_dontwant:
      name: "name_dontwant"
      description: "Return only neighbor nodes whose field *name* does *not* match any value 
                    in the provided list; if the list is empty, return all neighbor nodes 
                    regardless of their field *name*"
      in: query
      required: False
      schema:
        type: "array"
        items:
          type: "string"
          default: ""          # To prevent the word 'string' in the input field.
    category_want:
      name: "category_want"
      description: "Return only neighbor nodes whose field *category* matches any value 
                    in the provided list; if the list is empty, return all neighbor nodes 
                    regardless of their field *category*"
      in: query
      required: False
      schema:
        type: "array"
        items:
          type: "string"
          default: ""          # To prevent the word 'string' in the input field.
    category_dontwant:
      name: "category_dontwant"
      description: "Return only neighbor nodes whose field *category* does *not* match any value 
                    in the provided list; if the list is empty, return all neighbor nodes 
                    regardless of their field *category*"
      in: query
      required: False
      schema:
        type: "array"
        items:
          type: "string"
          default: ""          # To prevent the word 'string' in the input field.

tags:
  - name: Person
    description: "Everything related to persons in Ricgraph."
  - name: Organization
    description: "Everything related to organizations in Ricgraph."
  - name: Skill, expertise area or research area
    description: "Everything related to skills, expertise areas or research 
                  areas in Ricgraph (only if Ricgraph contains these entities)."
  - name: Advanced
    description: "REST API access to advanced Ricgraph functions."

paths:
  /person/search:
    get:
      operationId: "ricgraph_explorer.api_search_person"
      tags:
        - Person
      summary: "Search for a person"
      parameters:
        - $ref: "#/components/parameters/value"
        - $ref: "#/components/parameters/max_nr_items"
      responses:
        "200":
          description: "OK"
        "250":
          description: "Nothing found"
        "251":
          description: "Invalid search"
  /person/all_information:
    get:
      operationId: "ricgraph_explorer.api_person_all_information"
      tags:
        - Person
      summary: "Show all information related to this person"
      parameters:
        - $ref: "#/components/parameters/key"
        - $ref: "#/components/parameters/max_nr_items"
      responses:
        "200":
          description: "OK"
        "250":
          description: "Nothing found"
        "251":
          description: "Invalid search"
  /person/share_research_results:
    get:
      operationId: "ricgraph_explorer.api_person_share_research_results"
      tags:
        - Person
      summary: "Find persons that share any share research result types with this person"
      parameters:
        - $ref: "#/components/parameters/key"
        - $ref: "#/components/parameters/max_nr_items"
      responses:
        "200":
          description: "OK"
        "250":
          description: "Nothing found"
        "251":
          description: "Invalid search"
  /person/collaborating_organizations:
    get:
      operationId: "ricgraph_explorer.api_person_collaborating_organizations"
      tags:
        - Person
      summary: "Find organizations that this person collaborates with"
      description: "With this call you will get an overview of organizations that his person 
                    collaborates with. A person *X* from organization *A* collaborates with 
                    a person *Y* from organization *B* if *X* and *Y* have both contributed to 
                    the same research result."
      parameters:
        - $ref: "#/components/parameters/key"
        - $ref: "#/components/parameters/max_nr_items"
      responses:
        "200":
          description: "OK"
        "250":
          description: "Nothing found"
        "251":
          description: "Invalid search"
  /person/enrich:
    get:
      operationId: "ricgraph_explorer.api_person_enrich"
      tags:
        - Person
      summary: "Find information harvested from other source systems,
                not present in this source system"
      description: "The process of improving or enhancing information in a source 
                    system is called *enriching* that source system. This is only 
                    possible if you have harvested more than one source system. 
                    By using information found in one or more other harvested systems, 
                    information in this source system can be improved or enhanced.
                    With this call you can enter a name of one of your source systems. 
                    Ricgraph will show what information can be added to 
                    this source system, based on the information harvested from other 
                    source systems."
      parameters:
        - $ref: "#/components/parameters/key"
        - $ref: "#/components/parameters/source_system"
        - $ref: "#/components/parameters/max_nr_items"
      responses:
        "200":
          description: "OK"
        "250":
          description: "Nothing found"
        "251":
          description: "Invalid search"
  /organization/search:
    get:
      operationId: "ricgraph_explorer.api_search_organization"
      tags:
        - Organization
      summary: "Search for a (sub-)organization"
      parameters:
        - $ref: "#/components/parameters/value"
        - $ref: "#/components/parameters/max_nr_items"
      responses:
        "200":
          description: "OK"
        "250":
          description: "Nothing found"
        "251":
          description: "Invalid search"
  /organization/all_information:
    get:
      operationId: "ricgraph_explorer.api_organization_all_information"
      tags:
        - Organization
      summary: "Show all information related to this organization"
      parameters:
        - $ref: "#/components/parameters/key"
        - $ref: "#/components/parameters/max_nr_items"
      responses:
        "200":
          description: "OK"
        "250":
          description: "Nothing found"
        "251":
          description: "Invalid search"
  /organization/information_persons_results:
    get:
      operationId: "ricgraph_explorer.api_organization_information_persons_results"
      tags:
        - Organization
      summary: "Find any information from persons or their results in this organization"
      parameters:
        - $ref: "#/components/parameters/key"
        - $ref: "#/components/parameters/max_nr_items"
      responses:
        "200":
          description: "OK"
        "250":
          description: "Nothing found"
        "251":
          description: "Invalid search"
  /competence/search:
    get:
      operationId: "ricgraph_explorer.api_search_competence"
      tags:
        - Skill, expertise area or research area
      summary: "Search for a skill, expertise area or research area"
      parameters:
        - $ref: "#/components/parameters/value"
        - $ref: "#/components/parameters/max_nr_items"
      responses:
        "200":
          description: "OK"
        "250":
          description: "Nothing found"
        "251":
          description: "Invalid search"
  /competence/all_information:
    get:
      operationId: "ricgraph_explorer.api_competence_all_information"
      tags:
        - Skill, expertise area or research area
      summary: "Show all information related to this competence"
      parameters:
        - $ref: "#/components/parameters/key"
        - $ref: "#/components/parameters/max_nr_items"
      responses:
        "200":
          description: "OK"
        "250":
          description: "Nothing found"
        "251":
          description: "Invalid search"
  /broad_search:
    get:
      operationId: "ricgraph_explorer.api_broad_search"
      tags:
        - Advanced
      summary: "Search for anything (broad search)"
      parameters:
        - $ref: "#/components/parameters/value"
        - $ref: "#/components/parameters/max_nr_items"
      responses:
        "200":
          description: "OK"
        "250":
          description: "Nothing found"
        "251":
          description: "Invalid search"
  /advanced_search:
    get:
      operationId: "ricgraph_explorer.api_advanced_search"
      tags:
        - Advanced
      summary: "Advanced search"
      description: "The fields you enter are case-sensitive and use exact match search. 
                    If you enter values in more than one field, these fields are 
                    combined using AND."
      parameters:
        - $ref: "#/components/parameters/name"
        - $ref: "#/components/parameters/category"
        - $ref: "#/components/parameters/value"
        - $ref: "#/components/parameters/max_nr_items"
      responses:
        "200":
          description: "OK"
        "250":
          description: "Nothing found"
        "251":
          description: "Invalid search"
  /get_all_personroot_nodes:
    get:
      operationId: "ricgraph_explorer.api_get_all_personroot_nodes"
      tags:
        - Advanced
      summary: "Find all person-root nodes of this node"
      parameters:
        - $ref: "#/components/parameters/key"
        - $ref: "#/components/parameters/max_nr_items"
      responses:
        "200":
          description: "OK"
        "250":
          description: "Nothing found"
        "251":
          description: "Invalid search"
  /get_all_neighbor_nodes:
    get:
      operationId: "ricgraph_explorer.api_get_all_neighbor_nodes"
      tags:
        - Advanced
      summary: "Find all neighbor nodes of this node"
      parameters:
        - $ref: "#/components/parameters/key"
        - $ref: "#/components/parameters/name_want"
        - $ref: "#/components/parameters/name_dontwant"
        - $ref: "#/components/parameters/category_want"
        - $ref: "#/components/parameters/category_dontwant"
        - $ref: "#/components/parameters/max_nr_items"
      responses:
        "200":
          description: "OK"
        "250":
          description: "Nothing found"
        "251":
          description: "Invalid search"
