# ############################################################
# Config file for Python module linkchecker, to check
# whether all the internal and external links of the
# Ricgraph website and the Ricgraph documentation website
# are satisfied.

# You will need to install the linkchecker module:
# pip3 install linkchecker
#
# Run as one of the examples below:
# linkchecker --config=ricgraph-linkchecker.conf ../../ricgraph-documentation/build_website/index.html
# linkchecker --config=ricgraph-linkchecker.conf ../../ricgraph-documentation/build_documentation/index.html
# linkchecker --config=ricgraph-linkchecker.conf https://www.ricgraph.eu
# linkchecker --config=ricgraph-linkchecker.conf https://docs.ricgraph.eu
#
# Note that links that go through Cloudflare and the like
# will be reported as errors. They will report
# "Result Error: 403 Forbidden", while they are correct.
# This happens e.g. for DOI links.
#
# Original version Rik D.T. Janssen, June 2026.
# ############################################################

# Enable checking of correct/missing anchors in an HTML file.
# Missing anchors shown as warnings.
[AnchorCheck]

[output]
# Show all checked URLs (verbose).
verbose=0
# Log errors (broken links).
errors=1
# Log warnings (including missing anchors).
warnings=1
# Don't show progress status messages.
status=0
# Output format: text (also: html, csv, sql, xml, dot, gml, failures, none).
log=text

[filtering]
# Check only internal URLs (set to 1 to check external).
checkextern=1
# Do not warn about HTTP 301/302 redirects, follow them normally
# and only report if the final URL is broken (not 200 OK).
ignorewarnings=http-redirected
