name: Build and push Podman container for Ricgraph

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io/utrechtuniversity

      - name: Check current directory and files
        run: |
          pwd
          ls -la

      - name: Build Podman container for Ricgraph
        run: |
          podman build -f ../Containerfile -t ghcr.io/utrechtuniversity/ricgraph:latest .

      - name: Push Podman container for Ricgraph
        run: |
          podman push ghcr.io/utrechtuniversity/ricgraph:latest

