name: Build and push Podman container for Ricgraph

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

env:
  REGISTRY: ghcr.io/utrechtuniversity
  RICGRAPH_VERSION: 2.9

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}

      - name: Check current directory and files
        run: |
          pwd
          ls -la
          echo "Ricgraph registry: $REGISTRY"
          echo "Ricgraph version: $RICGRAPH_VERSION"

      - name: Build Podman container for Ricgraph
        run: |
          podman build -f Containerfile -t ${{ env.REGISTRY }}/ricgraph:${{ env.RICGRAPH_VERSION }} .

      - name: Update 'latest' tag for Podman container for Ricgraph
        run: |
          podman tag ${{ env.REGISTRY }}/ricgraph:${{ env.RICGRAPH_VERSION }} ${{ env.REGISTRY }}/ricgraph:latest

      - name: Push Podman containers for Ricgraph
        run: |
          podman push ${{ env.REGISTRY }}/ricgraph:${{ env.RICGRAPH_VERSION }}
          podman push ${{ env.REGISTRY }}/ricgraph:latest

